Repository kyma-incubator/sap-btp-service-operator, pull requests merged in 2023-01, with the labels that each got.

#25 Update to v0.3.6
  chart/Chart.yaml
  chart/templates/crd.yml
  chart/templates/deployment.yml
  chart/templates/service.yml
  chart/values.yaml
Labels: lgtm, size/L, area/service-management

#27 Update the OWNERS file
  OWNERS
Labels: documentation, lgtm, size/XS, area/service-management

#28 Update docs
  chart/README.md
Labels: lgtm, size/M, area/service-management, area/documentation
